### ISSUE TITLE
Upgrade front-end to use Material Design

### ISSUE THREAD

**Issue by carav008** [UMM-CSci-3601/3601-lab4_mongo-pre-S20#11]

**Comment by carav008** [comment]
Still working on looking upgrading using material design. As of now works but still need to understand more  of it

**Comment by kklamberty** [comment]
[user.component.html](https://github.com/UMM-CSci-3601/3601-lab4_mongo/blob/master/client/src/app/users/user.component.html) might benefit from being a [material list](https://material.angular.io/components/list/overview) instead of what it is currently, but other than that it seems that most of the html files are using mat components.
