### ISSUE TITLE
Add ability to reset after "Search for Company"

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab4_mongo-pre-S20#16]
At the moment, after you use "Search for Company" there's no way to reset back to all users, which is really awkward.

**Comment by kklamberty** [comment]
I have not added any tests for this yet. I must admit I'm not sure how to test this that would capture the error we were experiencing. The current test (the old test) didn't check that the url might not be what you intended or how to behave in that case. This code prevents some of those problems from happening, but I'm not certain of how to test that. It may need to be captured in an E2E test because it involves the input and the server both. Thoughts on that?
