### ISSUE TITLE
Clarify Rubric Items

### ISSUE THREAD

**Issue by bushw011** [UMM-CSci-3601/3601-lab4_mongo-pre-S20#26]
There's been some confusion when grading these labs in regards to what comments should go where. For instance, we have the Using Angular item, and the Displaying Todos in a Useful/ Pretty Way item on the rubric. I was assigned to grade people for the Using Angular item, and sometimes I said things that were likely repeated by Nic McPhee, who had the Displaying Todos item. This becomes particularly problematic when students are losing points multiple times on the rubric for the same thing.

**Comment by kklamberty** [comment]
The rubric now supports both tracking and grading in a more coherent manner. We decided to put the learning outcome of "Using Angular" (for example) in the rubric, but not for points. The points, then, just need to be tracked for the different aspects that were handled in the LABTASK. Multiple LABTASK elements contribute to your score for the learning goal so that we can track your progress on that learning outcome but you only earn or lose points for it within the LABTASK itself.
