### ISSUE TITLE
Do we want to replace anonymous `function`s with arrows (`=>`)?

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab4_mongo-pre-S20#81]
The Google JavaScript style guide recommends using arrows (`=>`) instead of the `function` keyword. So instead of:

```TypeScript
page.getUsers().then(function (users) {
            expect(users.length).toBe(2);
});
```

we'd use

```TypeScript
page.getUsers().then((users) => {
            expect(users.length).toBe(2);
});
```

There are a _lot_ of instances of anonymous functions with the `function` keyword, so switching to match this guideline would be quite a lot of work. I doubt we want to do it this semester, but the question then is whether we want to do it at all? Should there be an issue here that asks us to do this at some point down the road?

**Comment by kklamberty** [comment]
Yes - I think we should match that suggestion. It may be present in many places, but I bet it would be easy to update. Do you want me to tackle this? I think we should be sure to include a note somewhere for the students so that if they encounter either, they will know a little about what they are seeing. I'm happy to do this - it's my favorite kind of task - repetitive! :)

**Comment by NicMcPhee** [comment]
By all means have a go at it! I'll create an issue quick and assign it to you. :smile:
